name: Deploy main branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: echo ${{ secrets.dev.TST_SECRET }} && npm i
    - name: Print Secret Value
      run: echo ${{ secrets.TST_SECRET }}
    - name: Install Plugins and Deploy
      uses: serverless/github-action@v3.2
      with:
        args: -c "serverless plugin install -n serverless-plugin-typescript && serverless plugin install -n serverless-offline && serverless plugin install -n serverless-dotenv-plugin && serverless deploy --stage=${{ matrix.stages.stage }} --verbose"
        entrypoint: /bin/bash
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.dev.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.dev.AWS_SECRET_ACCESS_KEY }}
